# Generated by Django 3.2.14 on 2022-12-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start']},
        ),
        migrations.AddField(
            model_name='event',
            name='helpers',
            field=models.ManyToManyField(through='webapp.Volunteer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='helpers', to=settings.AUTH_USER_MODEL),
        ),
    ]
