# Generated by Django 3.2.14 on 2022-12-07 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20221206_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
