# Generated by Django 3.2.14 on 2022-12-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20221207_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cancelled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='cancelled',
            field=models.DateField(blank=True, null=True),
        ),
    ]
