# Generated by Django 3.2.14 on 2022-12-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20221207_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
