# Generated by Django 3.2.14 on 2022-12-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20221207_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
