# Generated by Django 3.2.14 on 2022-12-30 14:06

from django.db import migrations

def populate_end(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Event = apps.get_model('webapp', 'Event')
    for event in Event.objects.all():
        event.end = event.start+event.duration
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_event_end'),
    ]

    operations = [
        migrations.RunPython(populate_end),
    ]
