# Generated by Django 3.2.14 on 2022-12-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_address',
            field=models.EmailField(help_text="Email address for the event, defaults to owner's address", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.CharField(blank=True, help_text='Purpose of the event, helper skills required, etc.', max_length=128, null=True),
        ),
    ]
