# Generated by Django 3.2.14 on 2022-12-30 15:44

from django.db import migrations

def populate_contact_address(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Event = apps.get_model('webapp', 'Event')
    for event in Event.objects.all():
        event.contact_address = event.owner.email
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20221230_1547'),
    ]

    operations = [
        migrations.RunPython(populate_contact_address)
    ]
