# Generated by Django 3.2.14 on 2023-01-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_event_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner_reminded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_address',
            field=models.EmailField(blank=True, help_text="Contact email address for the event, defaults to owner's address", max_length=254, null=True),
        ),
    ]
