# Generated by Django 3.2.14 on 2023-01-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20230102_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alerts',
            field=models.BooleanField(default=False),
        ),
    ]
