# Generated by Django 3.2.14 on 2023-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_event_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.CharField(blank=True, help_text='Purpose of the event, helper skills required, etc.', max_length=200, null=True),
        ),
    ]
