# Generated by Django 3.2.14 on 2023-02-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_event_helpers_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='cancelled',
        ),
    ]
