# Generated by Django 3.2.14 on 2023-02-19 13:25

from django.db import migrations

from django.db.models.indexes import Index

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_remove_volunteer_cancelled'),
    ]

    operations = [
        migrations.AddIndex('volunteer', Index(fields=['event'], name='event_index')),
        migrations.RemoveConstraint(
            model_name='volunteer',
            name='only_volunteer_once',
        ),
    ]
