# Generated by Django 3.2.14 on 2023-02-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_remove_volunteer_only_volunteer_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='declined',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='withdrawn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
