# Generated by Django 3.2.14 on 2023-02-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20230219_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['created']},
        ),

    ]
