# Generated by Django 3.2.14 on 2022-12-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
