# Generated by Django 3.2.14 on 2022-12-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_user_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_validated',
            field=models.DateTimeField(blank=True, help_text='Timestanp of email address validation', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='send_notifications',
            field=models.BooleanField(default=True, help_text='Send email reminders and other messages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cancelled',
            field=models.DateTimeField(blank=True, help_text='Timestamp of account cancellation', null=True),
        ),
    ]
