# Generated by Django 3.2.14 on 2022-12-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_auto_20221230_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='email_validated',
            field=models.DateTimeField(blank=True, help_text='Timestamp of email address validation', null=True),
        ),
    ]
