# Generated by Django 3.2.14 on 2022-12-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_alter_user_email_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='send_notifications',
            field=models.BooleanField(default=True, help_text='Send email reminders and other messages', verbose_name='send email notifications'),
        ),
    ]
