# Generated by Django 3.2.14 on 2023-01-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_auto_20230112_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspended',
            field=models.DateTimeField(blank=True, help_text='Timestamp of suspension', null=True),
        ),
    ]
