# Generated by Django 3.2.14 on 2023-01-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_user_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.DateTimeField(blank=True, help_text='Timestamp of approval', null=True),
        ),
    ]
