# Generated by Django 3.2.14 on 2023-01-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0009_user_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('admiistrator', 'Is system administrator')]},
        ),
    ]
