# Generated by Django 3.2.14 on 2023-01-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0011_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tower',
            field=models.CharField(blank=True, help_text='Where you normally ring', max_length=50),
        ),
    ]
