# Generated by Django 3.2.14 on 2023-01-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0012_user_tower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tower',
            field=models.CharField(help_text='Where you normally ring', max_length=50),
        ),
    ]
