# Generated by Django 3.2.14 on 2023-01-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0014_auto_20230128_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='send_notifications',
            field=models.BooleanField(default=True, help_text='Send email alerts and reminders about your events', verbose_name='send event emails'),
        ),
        migrations.AlterField(
            model_name='user',
            name='send_other',
            field=models.BooleanField(default=True, verbose_name='send other emails'),
        ),
    ]
