# Generated by Django 3.2.14 on 2023-02-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0015_auto_20230129_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
