# Generated by Django 3.2.14 on 2023-03-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0017_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional, useful in case of last-minute cancellations or changes of plan', max_length=64),
        ),
    ]
