# Generated by Django 3.2.14 on 2025-08-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0018_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='volunteer_celebration',
            field=models.IntegerField(default=1, help_text='Highest volunteer count celebrated'),
        ),
    ]
