# Generated by Django 3.2.14 on 2025-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0019_user_volunteer_celebration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='volunteer_celebration',
            field=models.IntegerField(default=0, help_text='Highest volunteer count celebrated'),
        ),
    ]
