# Generated by Django 5.2.6 on 2025-09-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0020_alter_user_volunteer_celebration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_blocked',
            field=models.DateTimeField(blank=True, help_text='Timestamp of email suspension', null=True),
        ),
    ]
